# Generated by Django 5.1.5 on 2025-01-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_rename_carros_carro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marca_carro', to='carros.marca'),
        ),
    ]
