# Generated by Django 5.1.5 on 2025-01-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_marca_alter_carro_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='carros/'),
        ),
        migrations.AddField(
            model_name='carro',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
